### ISSUE TITLE
[BUG]: Issue template titles are difficult to follow

### ISSUE THREAD

**Issue by dlh01** [alleyinteractive/.github#33]
### Description of the bug

In this repository, the three issue templates supply prefixes to new issue titles:

* `[BUG]:`
* `[DOCS]:`
* `[FEATURE]:`

Now that I've seen some issues hit our repositories with these templates, I've found these prefixes a little difficult to read, for a few reasons:

* Issues are already being assigned a label based on the issue type. Why does the type need to also be in the title?
* Since the issue types in brackets function more as metadata, not prose, I don't think the colon after the brackets serves a purpose. A colon introduces text, but with the brackets, there's nothing before the colon to do the introducing. `BUG:` or `[BUG]` makes sense to me, but not `[BUG]:`.
* If the types need to be in the title, do they have to be IN ALL CAPS? 😱

I'm curious to know whether repo maintainers find value in having the type in the title, and, if so, whether we could tone down the type to `[Bug]`, `[Docs]`, and `[Feature]`. Otherwise, I would hope we could remove the prefixes from the titles and lean on the labels to provide that metadata.

### Steps To Reproduce

1. Open an issue in one of Alley's repositories.
2. Observe that the issue title has a prefix in all caps, a questionable colon after the prefix, and an identical label 😆

**Comment by mboynes** [comment]
Agreed, want to make a PR to address this?

**Comment by dlh01** [comment]
Sure! Which of the possible changes do you think I should make?

**Comment by mboynes** [comment]
I vote to remove the prefix entirely
