### ISSUE TITLE
Add persistent object cache to phpunit tests

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/.github#46]
### Description

Currently, the phpunit tests don't install either memcache or redis, and therefore tests are run without a persistent object cache present. Ideally, we would have a configuration available to let us specify which caching engine we are using and how we are integrating with it (e.g., object-cache.php present in repo vs. needing to be copied from elsewhere). This would support testing against VIP environments and Pantheon environments.

### Use Case

When a user uses this action, they should be able to configure it to use the persistent object cache provider of their choice.

**Comment by srtfisher** [comment]
Mantle does support setting up the `object-cache.php` file via https://mantle.alley.com/docs/testing/installation-manager#including-memcache-object-cache-drop-in but the action needs to be updated to actually setup Memcache/Redis.
