### ISSUE TITLE
Apply Labels Universally

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/.github#59]
### Description

I would like our new default labels to be applied to all of our open source repositories plus any non-client private repos that we have (e.g., broadway, production-docs).

- For labels that don't exist, create the label and apply the same description and color that are in use in the default labels list.
- For labels that do exist, apply the description and color from the default labels list, if it differs from what is defined in the repo.

### Use Case

As a member of the technology department, I want to be able to use consistent labeling on issues when preparing items for the tech department priorities board.

**Comment by benpbolton** [comment]
Using:
```
{
  "accessibility": {"description": "Improving the accessibility of an interface", "color": "ffffff"},
  "bug": {"description": "Something isn't working", "color": "d73a4a"},
  "ci/cd": {"description": "PR checks, deploys, automation", "color": "D1F31C"},
  "css": {"description": "Requires understanding CSS/SCSS", "color": "370936"},
  "devops": {"description": "Tooling and workflow improvements", "color": "424C47"},
  "documentation": {"description": "Improvements or additions to documentation", "color": "0075ca"},
  "elasticsearch": {"description": "Requires understanding Elasticsearch", "color": "FD2C0A"},
  "enhancement": {"description": "New feature or request", "color": "a2eeef"},
  "good first issue": {"description": "Good for newcomers", "color": "7057ff"},
  "gutenberg": {"description": "Requires understanding Gutenberg", "color": "2397C2"},
  "javascript": {"description": "Requires understanding JavaScript", "color": "168700"},
  "php": {"description": "Requires understanding PHP", "color": "435FEC"},
  "shell": {"description": "Requires understanding shell scripting", "color": "5D1D17"},
  "typescript": {"description": "Requires understanding TypeScript", "color": "0BF4A9"},
  "ux": {"description": "Designing and implementing user experience improvements", "color": "B69856"}
}

```

from https://github.com/alleyinteractive/production-docs/edit/main/general/department-project.md...

**Comment by benpbolton** [comment]
It's somewhat tedious/complex/error prone to exclude client private repos - I'll proceed updating all the labels (excepting archived), and if needed, we can go back after-the-fact and strip some labels out if needed.
