### ISSUE TITLE
Review `--generate-notes` usage

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/.github#61]
### Description

When creating a built release, the notes generated don't take into account the previous version but all commits.

https://github.com/alleyinteractive/.github/blob/main/.github/workflows/built-release.yml#L161-L163

### Use Case

Here is an example: https://github.com/alleyinteractive/wp-curate/releases/tag/v1.4.1

I'd expect see only the notes since 1.4.0, not since the first pull request was merged.

**Comment by kevinfodness** [comment]
Possible solution:

- On merge to `develop`, auto-merge changes to `develop-built` and run the build there and commit the result.
- Then, create release tags on the `develop-built` branch instead of an orphaned branch. This might be able to better incorporate changelog entries between releases.

**Comment by srtfisher** [comment]
With some [testing here](https://github.com/srtfisher/test-github-releases/releases) per @benpbolton's suggestion, we're going to move to a `*-built` branch for release cutting and then use that branch to tag the release. This will prevent orphan releases/commits and fix the changelog for releases.
