### ISSUE TITLE
Setup domain for GitHub Pages

### ISSUE THREAD

**Issue by srtfisher** [alleyinteractive/.github#67]
### Description

I would like to be able to use `code.alley.com` as a domain for Alley's GitHub pages.

### Use Case

When a GitHub page is created for a repository under `alleyinteractive` it should live on the `code.alley.com` subdomain.

**Comment by benpbolton** [comment]
we can now use any *alley.dev* domain (I've verified it). Steps would be to pick your repo (eg. alley-scripts) add a domain (eg. alley-scripts.alley.dev), open up DNS management (cloudflare, etc) add a CNAME for alleyinteractive.github.io for your record (eg. a CNAME for alley-scripts.alley.dev -> alleyinteractive.github.io ) and wait for things to settle out after saving the Github repo config...
