### ISSUE TITLE
Allow building of project during testing

### ISSUE THREAD

**Issue by anubisthejackle** [alleyinteractive/.github#86]
### Description

I would like to see the ability to execute NPM install and NPM scripts during the testing process.

### Use Case

Currently some of our projects (see wp-conditional-blocks) are failing during the testing phase because the build process copies the PHP files to the `/build` directory. If they aren't present there it doesn't include them. The use case for this change is that we could cause this build to happen prior to testing, thus allowing us to test this code correctly.

**Comment by kevinfodness** [comment]
Moved this functionality to Alley's reusable actions, which makes this possible by using the node tests action before the php tests action.
